### ISSUE TITLE
requirement of anndata = "0.7.5" makes it impossible to load anndata saved with newer version (e.g. 0.8.0)

### ISSUE THREAD

**Issue by AlexanderAivazidis** [pinellolab/pyrovelocity#42]
Hi,

I have problems loading anndata objects after installing the pyro velocity environment. It seems like you have a requirement of:

anndata = "0.7.5"

can you change this to anndata = 0.8.0? See this issue for example explaining that new anndata objects cannot be loaded with the old anndata packages:

https://github.com/scverse/anndata/issues/698

Best wishes,

Alexander

**Comment by qinqian** [comment]
Hi Alexander, 

Thank you for the feedback! This behavior of `anndata` is weird. Are you using `poetry` or `bioconda` way to install the package? I'll spend some time fix this error later. 

Best,
Alvin

**Comment by AlexanderAivazidis** [comment]
Hi Alvin,

thanks for getting back. I have used bioconda.

**Comment by AlexanderAivazidis** [comment]
Would be great to fix this! I haven't found a way to work around this problem, so it basically prevents me from using the package with the anndata objects I have.

**Comment by qinqian** [comment]
Sorry for the delay. I just came back from vacation, will explore this problem this week.

**Comment by qinqian** [comment]
Hi Alex, 

I tested on my side on the google cloud using notebook instance, please refer to [here](https://github.com/pinellolab/pyrovelocity/tree/master/reproducibility/environment). A simple way to upgrade the `anndata` without breaking the other package is to `conda activate pyrovelocity && pip install -U anndata==0.8.0rc1`. Please let me know if this works for you. To build another `bioconda` package, however there are a few conflicts during `conda-build` with `anndata==0.8.0`, I still need some time to submit another bioconda version for one-liner installation. Thanks!

**Comment by AlexanderAivazidis** [comment]
Thanks! That seems to be working for now.

**Comment by cameronraysmith** [comment]
Hi Alex,

We do plan to update all outdated dependencies to latest stable versions. However, until we are able to do that, the instructions in https://github.com/pinellolab/pyrovelocity/tree/8ec0b77d8a69b22708dc4639fa2b1332161acfe5/reproducibility/environment with manual overrides as suggested by Alvin should generally allow use of the library.

We will close this issue for now. Many thanks!
