### ISSUE TITLE
ModuleNotFoundError: No module named 'sparse'

### ISSUE THREAD

**Issue by AlexanderAivazidis** [pinellolab/pyrovelocity#651]
## description

I get this below error when importing pyrovelocity since rebasing to the beta branch recently and using the Python 3.11.9 environment:

## example

![image](https://github.com/user-attachments/assets/6fe45330-6f56-4878-b630-27eb938d352b)

**Comment by cameronraysmith** [comment]
The [sparse](https://github.com/pydata/sparse) package was added as a dependency in https://github.com/pinellolab/pyrovelocity/commit/3ab825d32d06a94e4c96a76038bb6c54432177de .
It's probably necessary to synchronize any local virtual environment with the updated pyproject dependency or reinstall the dependencies into a new virtual environment.

<details><summary>update virtualenv dependencies</summary>

<p>

```shell
poetry install --with lint,test,docs,workflows,bioinformatics --sync --dry-run
...
poetry install --with lint,test,docs,workflows,bioinformatics --sync
source .venv/bin/activate
```

</p>
</details>

**Comment by AlexanderAivazidis** [comment]
thanks, updating existing development virtualenv dependencies like this solved it: poetry install --with lint,test,docs,workflows,bioinformatics --sync
