### ISSUE TITLE
meet an error about poisson distribution support

### ISSUE THREAD

**Issue by rong-hash** [pinellolab/pyrovelocity#77]
- pyrovelocity version: 0.1.1
- Python version: 3.8
- Operating System: Linux

### Description

I tried to use the model to run my data, but met an error like this
```
ValueError: Expected value argument (Tensor of shape (500, 2000)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution Poisson(rate: torch.Size([500, 2000])), but found invalid values: tensor([[0.0000, 0.0000, 0.0000, ..., 0.0000, 1.6010, 1.0000], [1.8628, 0.0000, 0.0000, ..., 0.0000, 0.0000, 0.0000],

...

st_norm dist 500 2000 | value 500 2000 | log_prob 500 2000 | u dist 500 2000 | value 500 2000 |

```
My code is like:
```
from pyrovelocity.api import train_model

# import os

# os.environ['CUDA_VISIBLE_DEVICES']='0'

# Model 1

num_epochs = 1000 # large data

# num_epochs = 4000 # small data

adata_model_pos = train_model(adata,

                               max_epochs=num_epochs, svi_train=True, log_every=100,

                               patient_init=45,

                               batch_size=500, use_gpu=False, cell_state='state_info',

                               include_prior=True,

                               offset=False,

                               library_size=True,

                               patient_improve=1e-3,

                               model_type='auto',

                               guide_type='auto_t0_constraint',

                               train_size=1.0)
```
adata is the data I have, with information like this
```
AnnData object with n_obs × n_vars = 3060 × 37007 obs: 'cluster', 'label_time', 'nGene', 'nUMI', 'obs_names', 'time' var: 'gene_short_name', 'var_names' layers: 'matrix', 'spliced', 'unspliced'.
```
Is there any constraint on the adata? I would appreciate it so much if someone could give me a hand.

**Comment by qinqian** [comment]
Yes, the errors mean the gene expression `spliced` or `unspliced` have been normalized to float values, which are not supported as observations in `Poisson` distribution, in `pyrovelocity`, we constraint the adata to contain raw read count tables with integers.

**Comment by rong-hash** [comment]
> Yes, the errors mean the gene expression `spliced` or `unspliced` have been normalized to float values, which are not supported as observations in `Poisson` distribution, in `pyrovelocity`, we constraint the adata to contain raw read count tables with integers.

Thank you so much! Problem solved! Wish you publish your work in nature ASAP. 😄
